name: Publish
on: [ pull_request, push ]
jobs:
  publish:
#    environment:
#      name: maven-central
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5
